/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopManagementRouteImport } from './routes/top-management'
import { Route as RegistrationCybercafesRouteImport } from './routes/registration-cybercafes'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as NhiaEnrolmentRouteImport } from './routes/nhia-enrolment'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TopManagementRoute = TopManagementRouteImport.update({
  id: '/top-management',
  path: '/top-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationCybercafesRoute = RegistrationCybercafesRouteImport.update({
  id: '/registration-cybercafes',
  path: '/registration-cybercafes',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const NhiaEnrolmentRoute = NhiaEnrolmentRouteImport.update({
  id: '/nhia-enrolment',
  path: '/nhia-enrolment',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faqs': typeof FaqsRoute
  '/locations': typeof LocationsRoute
  '/nhia-enrolment': typeof NhiaEnrolmentRoute
  '/publications': typeof PublicationsRoute
  '/registration-cybercafes': typeof RegistrationCybercafesRoute
  '/top-management': typeof TopManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faqs': typeof FaqsRoute
  '/locations': typeof LocationsRoute
  '/nhia-enrolment': typeof NhiaEnrolmentRoute
  '/publications': typeof PublicationsRoute
  '/registration-cybercafes': typeof RegistrationCybercafesRoute
  '/top-management': typeof TopManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/faqs': typeof FaqsRoute
  '/locations': typeof LocationsRoute
  '/nhia-enrolment': typeof NhiaEnrolmentRoute
  '/publications': typeof PublicationsRoute
  '/registration-cybercafes': typeof RegistrationCybercafesRoute
  '/top-management': typeof TopManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faqs'
    | '/locations'
    | '/nhia-enrolment'
    | '/publications'
    | '/registration-cybercafes'
    | '/top-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faqs'
    | '/locations'
    | '/nhia-enrolment'
    | '/publications'
    | '/registration-cybercafes'
    | '/top-management'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/departments'
    | '/faqs'
    | '/locations'
    | '/nhia-enrolment'
    | '/publications'
    | '/registration-cybercafes'
    | '/top-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  FaqsRoute: typeof FaqsRoute
  LocationsRoute: typeof LocationsRoute
  NhiaEnrolmentRoute: typeof NhiaEnrolmentRoute
  PublicationsRoute: typeof PublicationsRoute
  RegistrationCybercafesRoute: typeof RegistrationCybercafesRoute
  TopManagementRoute: typeof TopManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-management': {
      id: '/top-management'
      path: '/top-management'
      fullPath: '/top-management'
      preLoaderRoute: typeof TopManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-cybercafes': {
      id: '/registration-cybercafes'
      path: '/registration-cybercafes'
      fullPath: '/registration-cybercafes'
      preLoaderRoute: typeof RegistrationCybercafesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nhia-enrolment': {
      id: '/nhia-enrolment'
      path: '/nhia-enrolment'
      fullPath: '/nhia-enrolment'
      preLoaderRoute: typeof NhiaEnrolmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  FaqsRoute: FaqsRoute,
  LocationsRoute: LocationsRoute,
  NhiaEnrolmentRoute: NhiaEnrolmentRoute,
  PublicationsRoute: PublicationsRoute,
  RegistrationCybercafesRoute: RegistrationCybercafesRoute,
  TopManagementRoute: TopManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
